# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MaterialDesignSearchUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaterialDesignSearchUI
  pod 'MaterialDesignWidgets', :path => '~/Documents/Github/material-design-widgets-lite-ios/MaterialDesignWidgets'
  
  target 'MaterialDesignSearchUIUITests' do
    # Pods for testing
  end

end
